
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Felix_Jerome
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form POS
     */
int sum = 0;
int qty;
int price;
int total;
int change = 0;
    public POS(String baristaName) {
        initComponents();
        lblBarista.setText(baristaName);
//        POS barista = new POS();
//        String baristaName = barista.getbaristaName();


        
        
        
//        Product toast = new Product();
//        toast.itemName = "French Toast";
//        toast.itemPrice = 160;
//        toast.itemQty = 0;
//        toast.itemTotal = 0;

    
    }
    
//    public POS(String baristaName) {
//        initComponents();
//        lblBarista.setText(baristaName);
//    }


//public class Product {
//    String itemName;
//    int itemPrice;
//    int itemQty;
//    int itemTotal;
//    
//}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBarista = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnToast = new javax.swing.JButton();
        btnCinnamon = new javax.swing.JButton();
        btnPancake = new javax.swing.JButton();
        btnHamNEgg = new javax.swing.JButton();
        btnBagel = new javax.swing.JButton();
        btnSausage = new javax.swing.JButton();
        btnDonut = new javax.swing.JButton();
        btnCroissant = new javax.swing.JButton();
        btnSandwich = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAmericano = new javax.swing.JButton();
        btnEspresso = new javax.swing.JButton();
        btnMacchiato = new javax.swing.JButton();
        btnMocha = new javax.swing.JButton();
        btnLatte = new javax.swing.JButton();
        btnCappuccino = new javax.swing.JButton();
        btnFrappuccino = new javax.swing.JButton();
        btnArabica = new javax.swing.JButton();
        btnTea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtChange = new javax.swing.JTextField();
        btnVoid = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("COFFEE SHOP P.O.S.");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Barista Name:");

        lblBarista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBarista.setText("Null");
        lblBarista.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblBaristaPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBarista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(319, 319, 319))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBarista))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOOD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        btnToast.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnToast.setText("French Toast");
        btnToast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToastActionPerformed(evt);
            }
        });

        btnCinnamon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCinnamon.setText("Cinnamon");
        btnCinnamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinnamonActionPerformed(evt);
            }
        });

        btnPancake.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPancake.setText("Pancake");
        btnPancake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPancakeActionPerformed(evt);
            }
        });

        btnHamNEgg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnHamNEgg.setText("Ham & Egg");
        btnHamNEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamNEggActionPerformed(evt);
            }
        });

        btnBagel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBagel.setText("Wheat Bagel");
        btnBagel.setActionCommand("");
        btnBagel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagelActionPerformed(evt);
            }
        });

        btnSausage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSausage.setText("Sausage Roll");
        btnSausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSausageActionPerformed(evt);
            }
        });

        btnDonut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDonut.setText("Glazed Donut");
        btnDonut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonutActionPerformed(evt);
            }
        });

        btnCroissant.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCroissant.setText("Croissant");
        btnCroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCroissantActionPerformed(evt);
            }
        });

        btnSandwich.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSandwich.setText("Sandwich");
        btnSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSandwichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnToast, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCinnamon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPancake, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHamNEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBagel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSausage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCroissant, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCinnamon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPancake, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHamNEgg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBagel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSausage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCroissant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BEVERAGES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        btnAmericano.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAmericano.setText("Americano");
        btnAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmericanoActionPerformed(evt);
            }
        });

        btnEspresso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEspresso.setText("Espresso");
        btnEspresso.setActionCommand("");
        btnEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspressoActionPerformed(evt);
            }
        });

        btnMacchiato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnMacchiato.setText("Macchiato");
        btnMacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMacchiatoActionPerformed(evt);
            }
        });

        btnMocha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnMocha.setText("Mocha");
        btnMocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMochaActionPerformed(evt);
            }
        });

        btnLatte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLatte.setText("Cafe Latte");
        btnLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatteActionPerformed(evt);
            }
        });

        btnCappuccino.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCappuccino.setText("Cappuccino");
        btnCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCappuccinoActionPerformed(evt);
            }
        });

        btnFrappuccino.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFrappuccino.setText("Frappuccino");
        btnFrappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrappuccinoActionPerformed(evt);
            }
        });

        btnArabica.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnArabica.setText("Arabica Coffee");
        btnArabica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArabicaActionPerformed(evt);
            }
        });

        btnTea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTea.setText("Green Tea");
        btnTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMacchiato, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMocha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnFrappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArabica, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMacchiato, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMocha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArabica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("TOTAL");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setText("CASH");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("CHANGE");

        txtCash.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtChange.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangeActionPerformed(evt);
            }
        });

        btnVoid.setBackground(new java.awt.Color(255, 51, 51));
        btnVoid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoid.setText("VOID TRANSACTION");
        btnVoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoidActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(0, 204, 102));
        btnPrint.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPrint.setText("PRINT RECEIPT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 51));
        btnUpdate.setText("Update");
        btnUpdate.setActionCommand("Update Changes");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal)
                            .addComponent(txtCash)
                            .addComponent(txtChange)))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCash)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtChange)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCinnamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinnamonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnCinnamon.getText(),
            price = 230,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnCinnamonActionPerformed

    private void btnBagelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagelActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnBagel.getText(),
            price = 210,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnBagelActionPerformed

    private void btnSausageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSausageActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnSausage.getText(),
            price = 225,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnSausageActionPerformed

    private void btnCroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCroissantActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnCroissant.getText(),
            price = 265,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnCroissantActionPerformed

    private void btnSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSandwichActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnSandwich.getText(),
            price = 195,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnSandwichActionPerformed

    private void btnEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspressoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnEspresso.getText(),
            price = 135,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnEspressoActionPerformed

    private void btnLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnLatte.getText(),
            price = 115,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnLatteActionPerformed

    private void btnCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCappuccinoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnCappuccino.getText(),
            price = 95,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnCappuccinoActionPerformed

    private void btnArabicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArabicaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnArabica.getText(),
            price = 165,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnArabicaActionPerformed

    private void btnTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnTea.getText(),
            price = 90,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnTeaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnToastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToastActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnToast.getText(),
            price = 220,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
        
        sum = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnToastActionPerformed

    private void btnPancakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPancakeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnPancake.getText(),
            price = 190,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnPancakeActionPerformed

    private void btnHamNEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamNEggActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnHamNEgg.getText(),
            price = 240,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnHamNEggActionPerformed

    private void btnDonutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonutActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnDonut.getText(),
            price = 235,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnDonutActionPerformed

    private void btnVoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoidActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        sum = 0;
        txtTotal.setText(Integer.toString(sum));
        txtCash.setText(Integer.toString(sum));
        txtChange.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnVoidActionPerformed

    private void txtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtChangeActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        // TODO add your handling code here:
        change = Integer.parseInt(txtCash.getText()) - Integer.parseInt(txtTotal.getText());
        txtChange.setText(Integer.toString(change));
    }//GEN-LAST:event_txtCashActionPerformed

    private void btnAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmericanoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnAmericano.getText(),
            price = 110,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnAmericanoActionPerformed

    private void btnMacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMacchiatoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnMacchiato.getText(),
            price = 150,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnMacchiatoActionPerformed

    private void btnMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMochaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnMocha.getText(),
            price = 120,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnMochaActionPerformed

    private void btnFrappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrappuccinoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[] {
            btnFrappuccino.getText(),
            price = 100,
            qty = 1, //+= for adding 1
            total = qty * price,
        });
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
        sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
    }
    
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnFrappuccinoActionPerformed

    private void lblBaristaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblBaristaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBaristaPropertyChange

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        sum = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++) {
//            String item = model.getValueAt(i, 0).toString();
//            price = Integer.parseInt(model.getValueAt(i, 1).toString());
//            qty = Integer.parseInt(model.getValueAt(i, 2).toString());
//            total = qty * price;
//            model.addRow(new Object[] {
//                item, price, qty, total
//            });
//            model.removeRow(i);
//            txtTotal.setText("0");
//                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
//                txtTotal.setText(Integer.toString(sum));
            price = Integer.parseInt(model.getValueAt(i, 1).toString());
            qty = Integer.parseInt(model.getValueAt(i, 2).toString());
            if(qty > 1) {
                total = qty * price;
                model.setValueAt(total, i, 3);
                
            }
            txtTotal.setText("0");
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            txtTotal.setText(Integer.toString(sum));
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        String total = txtTotal.getText();
        String cash = txtCash.getText();
        String change = txtChange.getText();
        
        new Receipt(model, total, cash, change).setVisible(true);
        
    }//GEN-LAST:event_btnPrintActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String baristaName = null;
                new POS(baristaName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmericano;
    private javax.swing.JButton btnArabica;
    private javax.swing.JButton btnBagel;
    private javax.swing.JButton btnCappuccino;
    private javax.swing.JButton btnCinnamon;
    private javax.swing.JButton btnCroissant;
    private javax.swing.JButton btnDonut;
    private javax.swing.JButton btnEspresso;
    private javax.swing.JButton btnFrappuccino;
    private javax.swing.JButton btnHamNEgg;
    private javax.swing.JButton btnLatte;
    private javax.swing.JButton btnMacchiato;
    private javax.swing.JButton btnMocha;
    private javax.swing.JButton btnPancake;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSandwich;
    private javax.swing.JButton btnSausage;
    private javax.swing.JButton btnTea;
    private javax.swing.JButton btnToast;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVoid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBarista;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
